name: Generate and Commit Unicode Mappings

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/empty.yml

permissions:
  contents: write   # allow pushing back to the repo

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.151.0
    strategy:
      matrix:
        prefix: [
          # Plane 15 (U+F0000–U+FFFFD)
          F00, F01, F02, F03, F04, F05, F06, F07, F08, F09,
          F0A, F0B, F0C, F0D, F0E, F0F,
          F10, F11, F12, F13, F14, F15, F16, F17, F18, F19,
          F1A, F1B, F1C, F1D, F1E, F1F,
          F20, F21, F22, F23, F24, F25, F26, F27, F28, F29,
          F2A, F2B, F2C, F2D, F2E, F2F,
          F30, F31, F32, F33, F34, F35, F36, F37, F38, F39,
          F3A, F3B, F3C, F3D, F3E, F3F,
          F40, F41, F42, F43, F44, F45, F46, F47, F48, F49,
          F4A, F4B, F4C, F4D, F4E, F4F,
          F50, F51, F52, F53, F54, F55, F56, F57, F58, F59,
          F5A, F5B, F5C, F5D, F5E, F5F,
          F60, F61, F62, F63, F64, F65, F66, F67, F68, F69,
          F6A, F6B, F6C, F6D, F6E, F6F,
          F70, F71, F72, F73, F74, F75, F76, F77, F78, F79,
          F7A, F7B, F7C, F7D, F7E, F7F,
          F80, F81, F82, F83, F84, F85, F86, F87, F88, F89,
          F8A, F8B, F8C, F8D, F8E, F8F,
          F90, F91, F92, F93, F94, F95, F96, F97, F98, F99,
          F9A, F9B, F9C, F9D, F9E, F9F,
          FA0, FA1, FA2, FA3, FA4, FA5, FA6, FA7, FA8, FA9,
          FAA, FAB, FAC, FAD, FAE, FAF,
          FB0, FB1, FB2, FB3, FB4, FB5, FB6, FB7, FB8, FB9,
          FBA, FBB, FBC, FBD, FBE, FBF,
          FC0, FC1, FC2, FC3, FC4, FC5, FC6, FC7, FC8, FC9,
          FCA, FCB, FCC, FCD, FCE, FCF,
          FD0, FD1, FD2, FD3, FD4, FD5, FD6, FD7, FD8, FD9,
          FDA, FDB, FDC, FDD, FDE, FDF,
          FE0, FE1, FE2, FE3, FE4, FE5, FE6, FE7, FE8, FE9,
          FEA, FEB, FEC, FED, FEE, FEF,
          FF0, FF1, FF2, FF3, FF4, FF5, FF6, FF7, FF8, FF9,
          FFA, FFB, FFC, FFD, FFE, FFF,

          # Plane 16 (U+100000–U+10FFFD)
          1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009,
          100A, 100B, 100C, 100D, 100E, 100F,
          1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019,
          101A, 101B, 101C, 101D, 101E, 101F,
          1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029,
          102A, 102B, 102C, 102D, 102E, 102F,
          1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039,
          103A, 103B, 103C, 103D, 103E, 103F,
          1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049,
          104A, 104B, 104C, 104D, 104E, 104F,
          1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059,
          105A, 105B, 105C, 105D, 105E, 105F,
          1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069,
          106A, 106B, 106C, 106D, 106E, 106F,
          1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079,
          107A, 107B, 107C, 107D, 107E, 107F,
          1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089,
          108A, 108B, 108C, 108D, 108E, 108F,
          1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099,
          109A, 109B, 109C, 109D, 109E, 109F,
          10A0, 10A1, 10A2, 10A3, 10A4, 10A5, 10A6, 10A7, 10A8, 10A9,
          10AA, 10AB, 10AC, 10AD, 10AE, 10AF,
          10B0, 10B1, 10B2, 10B3, 10B4, 10B5, 10B6, 10B7, 10B8, 10B9,
          10BA, 10BB, 10BC, 10BD, 10BE, 10BF,
          10C0, 10C1, 10C2, 10C3, 10C4, 10C5, 10C6, 10C7, 10C8, 10C9,
          10CA, 10CB, 10CC, 10CD, 10CE, 10CF,
          10D0, 10D1, 10D2, 10D3, 10D4, 10D5, 10D6, 10D7, 10D8, 10D9,
          10DA, 10DB, 10DC, 10DD, 10DE, 10DF,
          10E0, 10E1, 10E2, 10E3, 10E4, 10E5, 10E6, 10E7, 10E8, 10E9,
          10EA, 10EB, 10EC, 10ED, 10EE, 10EF,
          10F0, 10F1, 10F2, 10F3, 10F4, 10F5, 10F6, 10F7, 10F8, 10F9,
          10FA, 10FB, 10FC, 10FD, 10FE, 10FF
        ]
    steps:
      - name: Install Hugo
        run: |
          curl -sLJO "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz"
          mkdir -p "${HOME}/.local/hugo"
          tar -C "${HOME}/.local/hugo" -xf "hugo_${HUGO_VERSION}_linux-amd64.tar.gz"
          rm "hugo_${HUGO_VERSION}_linux-amd64.tar.gz"
          echo "${HOME}/.local/hugo" >> "${GITHUB_PATH}"

      - name: Verify installations
        run: |
          echo "Hugo: $(hugo version)"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            archetypes/

      - name: Generate mappings for prefix ${{ matrix.prefix }}
        run: |
          mkdir -p content/mappings
          seq $((0x${{ matrix.prefix }}00)) $((0x${{ matrix.prefix }}FF)) | \
          parallel -j4 '
            u={}
            if ! (((u>=0xF0000&&u<=0xFFFFD)||(u>=0x100000&&u<=0x10FFFD))); then exit 0; fi
            if ((u>=0xF0000&&u<=0xF021F)); then exit 0; fi
            if ((u>=0x1090EC&&u<=0x10FC5E)); then exit 0; fi
            if ((u<0x100000)); then h=$(printf "%05X" $u); else h=$(printf "%06X" $u); fi
            c=$(printf "\\U$(printf "%08x" $u)")
            hugo new "content/mappings/$h.md"
            if [ -f "content/mappings/$h.md" ]; then
              sed -i "s|^title:|title: $c|; s|^url:|url: $c|" "content/mappings/$h.md"
            fi
          '

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.prefix }}
          path: content/mappings

  commit:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: content/mappings

      - name: Commit and push all mappings
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Add generated mappings"
          file_pattern: content/mappings/**
