name: Update lastmod and trigger site build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'content/**/*.md'
      - .github/workflows/lastmod.yml

permissions:
  contents: write

jobs:
  update-lastmod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout module repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          sparse-checkout: |
            content/
            static/ivs/

      - name: Run script
        run: |
          rm -f static/ivs/*
          python ivs.py

      - name: Update lastmod and hex in changed MDs
        id: lastmod
        run: |
          if [[ "${{ github.event_name }}" == "push" || "${{ github.event_name }}" == workflow_dispatch ]]; then
            git diff --name-only --diff-filter=AM HEAD^ HEAD 'content/**/*.md' > changed_files.txt
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
            git diff --name-only --diff-filter=AM ${{ github.base_ref }} HEAD 'content/**/*.md' > changed_files.txt
          else
            echo "Unsupported event: ${{ github.event_name }}"
            exit 1
          fi
          if [[ -s changed_files.txt ]]; then
            cat changed_files.txt | python update_md.py >> $GITHUB_OUTPUT
          fi
          rm -f changed_files.txt

      - name: Get author
        id: author
        run: |
          echo "name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
          echo "email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_OUTPUT
          {
            echo "msg<<EOF"
            git log -1 --pretty=%B
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Amend commit with updated lastmod
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_options: '--amend --no-edit'
          commit_user_name: ${{ steps.author.outputs.name }}
          commit_user_email: ${{ steps.author.outputs.email }}
          commit_message: ${{ steps.author.outputs.msg }}
          push_options: '--force-with-lease'

      - name: Trigger site repo build
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: fsungfonts/fsungfonts.github.io
          event-type: module-updated
          client-payload: |
            {
              "module": "${{ github.repository }}",
              "commit": "${{ github.sha }}"
            }
